import React from 'react';
import QuantaidLogo from '@/assets/quantaid-logo.svg';

export const styles: { [key: string]: React.CSSProperties } = {
  loadingOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
  },
  spinner: {
    border: '8px solid #f3f3f3',
    borderTop: '8px solid #010117',
    borderRadius: '50%',
    width: '80px',
    height: '80px',
    animation: 'spin 2s linear infinite',
  },
  container: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'transparent',
    height: '100vh',
  },
  logoStyle: {
    position: 'absolute',
    top: '15px',
    left: '15px',
    height: '19px',
    width: '70px',
    minHeight: '19px',
    minWidth: '70px',
    zIndex: 1000,
    backgroundColor: '#F1E0E0',
    mask: `url(${QuantaidLogo}) no-repeat center`,
    maskSize: 'contain',
    WebkitMask: `url(${QuantaidLogo}) no-repeat center`,
    WebkitMaskSize: 'contain',
  },
  leftColumn: {
    position: 'relative',
    flex: 1,
    backgroundColor: '#1F305F',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4rem',
  },
  rightColumn: {
    flex: 1,
    backgroundColor: '#030E29',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#FFF',
    padding: '4rem',
  },
  formContainer: {
    maxWidth: '480px',
    width: '100%',
  },
  welcomeTitle: {
    marginBottom: '3rem',
    fontSize: '2.2rem',
    fontWeight: '400',
    color: '#F1E0E0',
    textAlign: 'center',
    fontFamily: "'Inter', sans-serif",
  },
  brandTitle: {
    marginBottom: '3rem',
    fontSize: '3rem',
    fontWeight: 'bold',
  },
  googleButton: {
    MozUserSelect: 'none',
    WebkitUserSelect: 'none',
    msUserSelect: 'none',
    WebkitAppearance: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto',
    backgroundColor: '#F2F2F2',
    backgroundImage: 'none',
    border: 'none',
    WebkitBorderRadius: '4px',
    borderRadius: '4px',
    WebkitBoxSizing: 'border-box',
    boxSizing: 'border-box',
    color: '#1F1F1F',
    fontFamily: "'Roboto', arial, sans-serif",
    fontSize: '16px',
    fontWeight: 500,
    letterSpacing: '0.25px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    height: '48px',
    width: '400px',
    maxWidth: '400px',
    minWidth: 'min-content',
    padding: '0 12px',
    position: 'relative',
    verticalAlign: 'middle',
    cursor: 'pointer',
    outline: 'none',
    overflow: 'hidden',
    WebkitTransition: 'background-color .218s, border-color .218s, box-shadow .218s',
    transition: 'background-color .218s, border-color .218s, box-shadow .218s',
  },
  googleIcon: {
    marginRight: '0.7rem',
    height: '26px',
  },
  divider: {
    display: 'flex',
    alignItems: 'center',
    margin: '2rem 0',
    marginTop: '3.4rem',
    marginBottom: '3.4rem',
    width: '100%',
  },
  line: {
    flex: 1,
    height: '1px',
    backgroundColor: '#ccc',
    margin: '0 -1rem',
    marginTop: '0.03rem',
  },
  dividerText: {
    margin: '0 1rem',
    color: '#BFC3D9',
    fontSize: '.7rem',
    whiteSpace: 'nowrap',
    backgroundColor: '#1F305F',
    padding: '0 0.5rem',
    position: 'relative',
    zIndex: 1,
  },
  inputContainer: {
    textAlign: 'left',
    marginBottom: '1.5rem',
  },
  label: {
    display: 'block',
    marginBottom: '0.3rem',
    color: '#F1E0E0',
    fontSize: '1.3rem',
  },
  input: {
    width: '100%',
    padding: '1rem',
    borderRadius: '4px',
    border: 'none',
    fontSize: '1.2rem',
    fontFamily: "'Inter', sans-serif",
    letterSpacing: '-0.01em',
    lineHeight: 1.2,
    backgroundColor: 'rgba(116, 142, 203, 1)',
    color: '#1F1A2A',
  },
  signupButton: {
    backgroundColor: '#2C5CE6',
    color: '#fff',
    padding: '1.2rem',
    width: '100%',
    border: 'none',
    borderRadius: '50px',
    cursor: 'pointer',
    fontSize: '1.3rem',
    fontFamily: "'Inter', sans-serif",
    fontWeight: '500',
    letterSpacing: '-0.01em',
    lineHeight: 1.2,
    margin: '2rem 0',
    transition: 'all 0.1s ease 0.05s',
  },
  labelText: {
    fontSize: '0.85rem',
    color: '#F1E0E0',
    lineHeight: 1.4,
    marginTop: '-0.4rem',
    marginBottom: '0.4rem',
    textAlign: 'left',
  },
  termsText: {
    fontSize: '0.9rem',
    color: '#B4B6BE',
    lineHeight: 1.4,
    textAlign: 'left',
  },
  forgotPasswordContainer: {
    textAlign: 'left',
    marginBottom: '0.5rem',
  },
  formError: {
    color: '#fa6060',
    fontSize: '0.85rem',
    marginBottom: '0.5rem',
    textAlign: 'center',
    fontFamily: "'Inter', sans-serif",
  },
  formMessage: {
    color: '#4ade80',
    fontSize: '0.85rem',
    marginBottom: '0.5rem',
    textAlign: 'center',
    fontFamily: "'Inter', sans-serif",
  },
  forgotPasswordLink: {
    background: 'none',
    border: 'none',
    color: '#A4C5FF',
    textDecoration: 'underline',
    fontSize: '0.9rem',
    cursor: 'pointer',
    fontFamily: "'Inter', sans-serif",
    padding: 0,
    fontWeight: '400',
  },
  loginLink: {
    marginTop: '0rem',
    fontSize: '1rem',
    color: '#C1C5D6',
    textAlign: 'center',
    fontWeight: '400',
  },
  toggleButton: {
    background: 'none',
    border: 'none',
    color: '#A4C5FF',
    textDecoration: 'none',
    fontSize: '1rem',
    cursor: 'pointer',
    fontFamily: "'Inter', sans-serif",
    padding: 0,
    fontWeight: '400',
  },
  linkStyle: {
    color: '#A4C5FF',
    textDecoration: 'underline',
    fontWeight: '400',
  },
  rightContent: {
    textAlign: 'center',
    maxWidth: '480px',
  },
  heading: {
    fontSize: '2.8rem',
    marginBottom: '0.8rem',
    fontWeight: 'bold',
    lineHeight: 1.2,
  },
  subheading: {
    fontSize: '1.8rem',
    lineHeight: 1.4,
  },
};
